### ISSUE TITLE
Rails6へのアップデート

### ISSUE THREAD

**Issue by Aseiide** [yatsuhashi168/taskleaf#60]
- Rails6へのアップデート

**Comment by eatplaynap** [comment]
Labelを付けてやりたいことをバラしてみました

**Comment by Aseiide** [comment]
たしかに、こっちのが分かり良いですね。あざます

**Comment by Aseiide** [comment]
今あるテストで十分なので、壊れたらその都度テストを追加する

**Comment by Aseiide** [comment]
- [Rails アップグレードガイド - Railsガイド](https://railsguides.jp/upgrading_ruby_on_rails.html)
- [永久保存版！？伊藤さん式・Railsアプリのアップグレード手順 - Qiita](https://qiita.com/jnchito/items/0ee47108972a0e302caf)

**Comment by Aseiide** [comment]
- [【前編】永久保存版！？伊藤さん式・Railsアプリのアップグレード手順 - YouTube](https://www.youtube.com/watch?v=hT68fhuWbHU)
- [【後編】永久保存版！？伊藤さん式・Railsアプリのアップグレード手順 - YouTube](https://www.youtube.com/watch?v=SnwNFMauzjM)

この動画でRails5からRails6へアップグレードしているらしい
