### ISSUE TITLE
Ruby2.5.1から2.7.5へのバージョンアップ

### ISSUE THREAD

**Issue by eatplaynap** [yatsuhashi168/taskleaf#61]

**Comment by Aseiide** [comment]
ruby 2.5.1 から ruby 3.1.0 にバージョンアップ

**Comment by Aseiide** [comment]
[永久保存版！？伊藤さん式・Railsアプリのアップグレード手順 - Qiita](https://qiita.com/jnchito/items/0ee47108972a0e302caf) によると、Railsのアップグレード #60 と一つにしても良いかもしれない
