### ISSUE TITLE
ログアウト機能がバグってる

### ISSUE THREAD

**Issue by eatplaynap** [yatsuhashi168/taskleaf#71]
![image](https://user-images.githubusercontent.com/63531341/151087148-bb99f261-ba74-4c02-9932-5ebddc302120.png)

↓ログ見るとGETが走ってる
```
Started GET "/logout" for ::1 at 2022-01-26 09:47:28 +0900
  
ActionController::RoutingError (No route matches [GET] "/logout"):
```

**Comment by haruguchi-yuma** [comment]
nodeのバージョが16系だったのでエラーが出ていた。
nodeのバージョンを12系にしたらうまく動いた。
