### ISSUE TITLE
Issueに取り掛かる前にカンバンを立てたい

### ISSUE THREAD

**Issue by haruguchi-yuma** [yatsuhashi168/taskleaf#74]
Github Projectsのカンバンを立てることによって進捗状況が把握できると思うので！ぜひ！:bow:

**Comment by Aseiide** [comment]
@haruguchi-yuma  雑にカンバンつくりました。輪読会で見せながらやったほうが良かったかな〜。チーム開発/自作サービスでやるからいいか
